### PR TITLE
Upgrade

### PR DESCRIPTION
**Pull request by yalh76**
## Problem

- *Level 0*

## Solution

- *Apply example_ynh*
- *Fix source checksum*
- *Fix services and logs*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Review by mhfowler — APPROVED** [review]
wow cool, its a little hard to see everything in such a big pr, 
but it looks like theres numerous improvements in here, cool!

**Comment by mhfowler** [comment]
I'm waiting for the next release of peachpub package which has some small improvements, 
then I'll share this package more widely

**Comment by yalh76** [comment]
> wow cool, its a little hard to see everything in such a big pr, but it looks like theres numerous improvements in here, cool!

I known it's big, it 's why I've separated into 3 commits, making it easier to read ^^

**Pull request merged**
