### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by yalh76**
## Problem

- *Level 0*

## Solution

- *[Apply last example_ynh](https://github.com/YunoHost-Apps/peachpub_ynh/commit/3a1332da63d7f6cd8d9d87a4079b5ef973af3a43)*
- *[Fix source checksum](https://github.com/YunoHost-Apps/peachpub_ynh/commit/2ebf83106c2b59af5332e7089b50885bb35d850d)*
- *[Fix services](https://github.com/YunoHost-Apps/peachpub_ynh/commit/d80aa110e536c06fd18b83502699d5f442c0123c)*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by mhfowler** [comment]
!testme

**Comment by mhfowler** [comment]
I've found the private install test is sometimes flaky for unclear reasons, but otherwise LG!

**Comment by yalh76** [comment]
> I've found the private install test is sometimes flaky for unclear reasons, but otherwise LG!

yes, it's a known problem.

we can merge ?

**Comment by mhfowler** [comment]
yes, I should have said that more clearly

**Pull request merged**
